export const eventConfig = {
  siteName: "GoldenHour Delhi",
  entityName: "GoldenHour",
  alternateName: "GoldenHour hackathon",
  siteUrl: "https://www.goldenhourdelhi.co.in",
  description: "GoldenHour V1 is a free, student-run 12-hour build day for participants aged 13–19 (under 20 on event day) in Delhi NCR.",
  date: "14 November 2026",
  dateShort: "14 November 2026",
  isoDate: "2026-11-14T08:00:00+05:30",
  endIsoDate: "2026-11-14T20:00:00+05:30",
  dateStatus: "TENTATIVE",
  venue: "Venue to be announced",
  location: "Delhi NCR, India",
  duration: "12 hours",
  activeBuildHours: "About 6 hours",
  entry: "Free",
  ageLimit: "Ages 13–19; must be under 20 on 14 November 2026",
  minimumAge: 13,
  teamSize: "1–3 participants",
  participantLimit: "Approximately 60 participants",
  registrationOpen: true,
  tracks: ["Web Development", "Game Development"],
  prizes: ["CodeCrafters VIP memberships", "GoldenHour trophies", "Certificates", "Stickers"],
  registrationUrl: "https://forms.gle/2om1zTVv5FCau56r5",
  guardianConsentUrl: "/guardian-consent",
  whatsappCommunityUrl: "https://chat.whatsapp.com/CpSkfYnkEmKAXURIWp7TQi",
  volunteerUrl: "https://forms.gle/R8cuBKNLj1ftXKfJ8",
  codeCraftersUrl: "https://www.codecrafters.io",
  osenUrl: "https://osen.live/",
  refreshmentPartner: "SEWAN FOODS",
  contactEmail: "hello@goldenhourdelhi.co.in",
  instagramUrl: "https://www.instagram.com/goldenhour.delhi/",
  linkedinUrl: "https://www.linkedin.com/company/goldenhourdelhi/",
  founders: ["Abhinav Goyal", "Divya"],
  leadOrganizers: ["Abhinav Goyal", "Divya", "Harsh", "Anurag"],
  coOrganizers: ["Yashpal Yadav"],
  lastUpdated: "2026-10-06",
} as const;

export const faqItems = [
  {
    q: "What is GoldenHour V1?",
    a: "GoldenHour V1 is a free, student-run 12-hour build day in Delhi NCR, scheduled for 14 November 2026 (tentative).",
    category: "ABOUT",
    detail: "The day runs from 8:00 AM to 8:00 PM India Standard Time, with about six hours of active build sprints. The venue is still to be announced.",
  },
  {
    q: "Who can participate?",
    a: "Participants must be at least 13 and under 20 on 14 November 2026 (ages 13–19 on the event date).",
    category: "ELIGIBILITY",
    detail: "At check-in, organizers may view a school ID, Aadhaar, passport, or birth certificate to verify age. They will not copy or store the document.",
  },
  {
    q: "Do participants under 18 need guardian consent?",
    a: "Yes. Participants under 18 need permission from a parent or legal guardian.",
    category: "SAFETY",
    detail: "Consent is requested in the registration form and a signed guardian consent slip must be brought to check-in. Use the printable slip linked in the registration section.",
  },
  {
    q: "What is the team size? Can designers or PMs join?",
    a: "Teams may have 1–3 participants, including solo builders.",
    category: "TEAMS",
    detail: "Designers and project managers are welcome as contributors on Web Development or Game Development teams.",
  },
  {
    q: "What tracks are available?",
    a: "Choose Web Development or Game Development.",
    category: "ABOUT",
    detail: "Projects should fit the selected track and be demonstrated at the event.",
  },
  {
    q: "May we use AI tools or code we wrote before the event?",
    a: "AI tools are allowed. Disclose the tools you used in your project README.",
    category: "RULES",
    detail: "You may use open-source libraries, templates, and your own reusable boilerplate. The project itself must be started at the event.",
  },
  {
    q: "How do we submit our project, and how will it be judged?",
    a: "Submit a public repository, a README, and a working demo link before the 5:00 PM IST hard deadline.",
    category: "RULES",
    detail: "Judging areas are functionality, technical implementation, user experience/design, and innovation/creativity. The organizers will publish any scoring weights before the event.",
  },
  {
    q: "What prizes are there, and how are they awarded?",
    a: "Winning teams receive GoldenHour trophies; CodeCrafters VIP memberships are awarded per participant.",
    category: "PRIZES",
    detail: "Membership durations differ by place. All participants also receive a GoldenHour sticker and a digital certificate.",
  },
  {
    q: "How do travel and accommodation work?",
    a: "Participants arrange their own travel. Overnight accommodation is not provided.",
    category: "LOGISTICS",
    detail: "This plan is provisional until the venue is confirmed. Participants under 18 need their parent or guardian to arrange their journey home.",
  },
  {
    q: "What if the date or venue changes?",
    a: "The published date is tentative and the venue has not yet been confirmed.",
    category: "LOGISTICS",
    detail: "If organizers make a change, they will update the event website and use registration contact details to communicate it.",
  },
  {
    q: "Will participants receive a certificate?",
    a: "Every participant receives a digital certificate of participation.",
    category: "LOGISTICS",
    detail: "Participants also receive an official GoldenHour sticker.",
  },
  {
    q: "How do I register?",
    a: "Registration is open through the official Google Form.",
    category: "REGISTRATION",
    detail: "The team leader submits one form for the team and includes each team member. Google sign-in is currently required by the form. Participants under 18 need parent/guardian consent and must bring a signed consent slip to check-in.",
  },
  {
    q: "What should I bring?",
    a: "Bring a laptop and charger, plus any hardware you want to use.",
    category: "LOGISTICS",
    detail: "The venue and final participant checklist will be announced when confirmed.",
  },
  {
    q: "Where can I read the safety rules or ask a question?",
    a: "Read the GoldenHour Code of Conduct before attending.",
    category: "SAFETY",
    detail: "For questions or to request access to or deletion of registration information, email hello@goldenhourdelhi.co.in.",
  },
] as const;

export const eventDateLabel = `${eventConfig.dateShort} (${eventConfig.dateStatus})`;
export const eventStatusLine = `${eventDateLabel}. Venue to be announced. Registration is open.`;
export const canonicalEventPath = "/goldenhour";
