import type { Metadata } from "next";
import Link from "next/link";
import { eventConfig } from "@/lib/event";
import { BreadcrumbStructuredData } from "@/components/StructuredData";
import { pageMetadata } from "../metadata";

export const metadata: Metadata = pageMetadata("About GoldenHour Delhi — Press and Media Kit", "GoldenHour Delhi is a student-run hackathon for builders under 19 in Delhi NCR. Find the official facts, founders, partners, brand usage, and contact details.", "/about", { url: "/og/about.png", width: 1200, height: 630, alt: "About GoldenHour Delhi" });

export default function AboutPage() {
  return <><BreadcrumbStructuredData items={[{ name: "GoldenHour Delhi", path: "/" }, { name: "About", path: "/about" }]} /><main className="min-h-screen bg-offwhite text-black px-5 md:px-12 py-24"><div className="max-w-[1000px] mx-auto"><Link href="/" className="font-space text-xs text-sunset hover:text-black">← BACK TO GOLDENHOUR DELHI</Link><p className="gh-kicker mt-12">PRESS / MEDIA KIT</p><h1 className="font-archivo text-6xl md:text-9xl leading-[.78] mt-5">ABOUT<br /><span className="text-sunset">GOLDENHOUR.</span></h1><section className="mt-16 max-w-3xl"><h2 className="font-archivo text-3xl md:text-5xl mb-5">OFFICIAL DESCRIPTION</h2><p className="font-dm text-lg leading-relaxed">{eventConfig.description} GoldenHour is organized by a student-led team and is designed for school and other student builders in Delhi NCR.</p></section><section className="mt-16 grid md:grid-cols-2 gap-6"><div className="brutal-card p-7"><h2 className="font-archivo text-3xl mb-5">FACT SHEET</h2><dl className="space-y-4 font-dm text-sm"><div><dt className="font-space text-[10px] font-bold">DATE</dt><dd>{eventConfig.date} — {eventConfig.dateStatus.toLowerCase()}</dd></div><div><dt className="font-space text-[10px] font-bold">VENUE</dt><dd>{eventConfig.venue}</dd></div><div><dt className="font-space text-[10px] font-bold">ELIGIBILITY</dt><dd>{eventConfig.ageLimit}</dd></div><div><dt className="font-space text-[10px] font-bold">TRACKS</dt><dd>{eventConfig.tracks.join(" and ")}</dd></div><div><dt className="font-space text-[10px] font-bold">STATUS</dt><dd>Registration opens {eventConfig.registrationOpening}</dd></div></dl></div><div className="brutal-card-orange p-7"><h2 className="font-archivo text-3xl mb-5">BRAND USAGE</h2><p className="font-dm text-sm leading-relaxed">Write “GoldenHour Delhi” for the organization and “GoldenHour V1” for the event. “GoldenHour hackathon” is acceptable when describing the event. Do not write “GoldenHacks” or “GOLDEN.HOUR” as the canonical entity name.</p><p className="font-space text-[10px] font-bold mt-6">LAST UPDATED: {eventConfig.lastUpdated}</p></div></section><section className="mt-16"><h2 className="font-archivo text-3xl md:text-5xl mb-5">FOUNDERS & PARTNERS</h2><p className="font-dm text-lg leading-relaxed">Founders named on the site: {eventConfig.founders.join(" and ")}. Event partner: DelhiHacks. Prize sponsor: CodeCrafters. Academic sponsor: OSEN.</p></section><section className="mt-16 border-t-2 border-black pt-8"><h2 className="font-archivo text-3xl mb-5">CONTACT</h2><address className="font-dm not-italic"><a className="underline text-sunset" href={`mailto:${eventConfig.contactEmail}`}>{eventConfig.contactEmail}</a><br /><a className="underline text-sunset" href={eventConfig.instagramUrl}>Instagram</a> · <a className="underline text-sunset" href={eventConfig.linkedinUrl}>LinkedIn</a></address></section></div></main></>;
}
