import Link from "next/link";
import { pageMetadata } from "../metadata";

export const metadata = pageMetadata(
  "Code of Conduct",
  "The GoldenHour Code of Conduct for participants, volunteers, organizers, judges, sponsors, guests, and event staff.",
  "/code-of-conduct",
);

type Section = { title: string; paragraphs?: string[]; bullets?: string[] };

const sections: Section[] = [
  { title: "1. Our Community Standards", paragraphs: ["Everyone at GoldenHour is expected to:"], bullets: ["Treat other participants, volunteers, organizers, sponsors, judges, and staff with respect.", "Communicate professionally and respectfully, even when disagreements occur.", "Give others a reasonable opportunity to speak, participate, and contribute.", "Respect different backgrounds, identities, experiences, skill levels, opinions, and abilities.", "Help create an environment where beginners feel comfortable asking questions and learning.", "Respect personal boundaries and consent.", "Follow reasonable instructions given by event organizers and venue staff.", "Take care of the event venue, equipment, and other people's property.", "Keep shared spaces clean and usable.", "Report safety concerns or inappropriate behavior to the organizers.", "Cooperate with reasonable investigations into reported incidents."],},
  { title: "2. Harassment Is Not Tolerated", paragraphs: ["GoldenHour has zero tolerance for harassment or abusive behavior.", "Harassment includes, but is not limited to:"], bullets: ["Offensive verbal or written comments.", "Threats or intimidation.", "Bullying or targeted humiliation.", "Unwanted sexual attention or comments.", "Unwanted physical contact.", "Repeated unwanted communication.", "Deliberately disrupting another participant's participation.", "Discriminatory comments or behavior.", "Sharing someone's private information without permission.", "Stalking or persistent unwanted following/contact.", "Retaliating against someone who reports an incident or assists with an investigation."],},
  { title: "3. Discrimination", paragraphs: ["GoldenHour does not tolerate discrimination or harassment based on characteristics such as:"], bullets: ["Race or ethnicity", "Nationality", "Religion or belief", "Gender or gender identity", "Sexual orientation", "Disability", "Age", "Appearance", "Socioeconomic background", "Educational background", "Technical experience", "Any other protected or personal characteristic"],},
  { title: "4. Physical Safety", paragraphs: ["All attendees must follow venue safety rules and reasonable instructions from organizers and venue personnel.", "Participants must not:"], bullets: ["Intentionally create unsafe situations.", "Damage venue infrastructure or equipment.", "Block emergency exits.", "Interfere with fire-safety equipment.", "Enter restricted areas.", "Fight or threaten physical violence.", "Tamper with electrical, networking, or other venue infrastructure.", "Use equipment in a way that creates a foreseeable safety risk."],},
  { title: "5. Respecting Privacy", paragraphs: ["Do not share another person's personal information without their permission.", "This includes:"], bullets: ["Phone numbers", "Personal email addresses", "Home addresses", "Identification documents", "Private conversations", "Private photographs or recordings", "Login credentials", "Private social-media information"],},
  { title: "6. Online Conduct", paragraphs: ["This Code of Conduct also applies to official GoldenHour online spaces connected to the event, including event communication channels and community spaces.", "Participants must not use these spaces to:"], bullets: ["Harass or threaten others.", "Spam or flood channels.", "Share malicious or abusive content.", "Impersonate another person.", "Dox or expose private information.", "Deliberately disrupt event communication.", "Target another participant with repeated unwanted messages."],},
  { title: "7. Projects, Code, and Intellectual Property", paragraphs: ["GoldenHour encourages participants to learn from one another, but participants must respect intellectual property.", "Participants must:"], bullets: ["Submit work that they are permitted to use.", "Give appropriate credit when using third-party code, libraries, assets, datasets, APIs, or other resources.", "Follow the licenses applicable to third-party resources.", "Not claim another person's work as their own.", "Not intentionally sabotage another team's project.", "Not access another team's private repository, accounts, systems, or data without permission."],},
  { title: "8. Cheating and Misrepresentation", paragraphs: ["Participants must not intentionally misrepresent their work.", "Examples include:"], bullets: ["Submitting a project created entirely by someone outside the registered team as if it were the team's work.", "Falsifying project information.", "Manipulating judging materials or demonstrations.", "Impersonating another participant.", "Intentionally providing false information to organizers.", "Interfering with another team's submission.", "Attempting to gain an unfair advantage through unauthorized access or manipulation of event systems."],},
  { title: "9. Venue and Property", paragraphs: ["Everyone is responsible for leaving the venue in reasonable condition.", "Participants and volunteers must:"], bullets: ["Respect venue property.", "Use furniture and equipment responsibly.", "Dispose of waste properly.", "Avoid unnecessary damage or modification to venue infrastructure.", "Return borrowed equipment when requested.", "Follow venue-specific rules."],},
  { title: "10. Volunteer Responsibilities", paragraphs: ["Volunteers are representatives of GoldenHour during the event.", "Volunteers are expected to:"], bullets: ["Treat all participants equally and respectfully.", "Avoid using their position to intimidate or pressure participants.", "Follow organizer instructions.", "Protect confidential information they receive through their role.", "Escalate serious incidents to the designated organizers rather than attempting to handle them alone.", "Avoid favoritism when assisting participants.", "Not interfere with judging or project evaluation unless their assigned role requires it.", "Maintain professional boundaries with participants."],},
  { title: "11. Organizer Responsibilities", paragraphs: ["GoldenHour organizers are responsible for maintaining a safe and respectful event environment.", "Organizers will:"], bullets: ["Take reports of misconduct seriously.", "Treat reports as confidential where reasonably possible.", "Assess reported incidents fairly.", "Take reasonable steps to protect people affected by an incident.", "Escalate serious safety concerns when appropriate.", "Cooperate with venue personnel or emergency services when necessary.", "Take appropriate action when this Code of Conduct is violated."],},
  { title: "12. Reporting an Incident", paragraphs: ["If you experience or witness behavior that violates this Code of Conduct, please report it to a GoldenHour organizer or designated event staff member as soon as reasonably possible.", "A report should include, where possible:"], bullets: ["What happened.", "When it happened.", "Where it happened.", "Who was involved.", "Names or descriptions of witnesses.", "Any relevant screenshots, messages, photographs, or other evidence."],},
  { title: "13. How Reports Are Handled", paragraphs: ["GoldenHour will review reports as promptly and fairly as reasonably possible.", "Depending on the circumstances, organizers may:"], bullets: ["Speak privately with the person who made the report.", "Speak with witnesses or other relevant people.", "Review available evidence.", "Give the reported person an opportunity to respond where appropriate.", "Take steps to protect people involved while the situation is reviewed.", "Determine appropriate action based on the circumstances and applicable rules."],},
  { title: "14. Possible Consequences", paragraphs: ["Violations may result in action appropriate to the seriousness and circumstances of the incident.", "Possible actions include:"], bullets: ["Verbal or written warning.", "Requirement to stop the behavior.", "Removal from a particular activity or area.", "Loss of event privileges.", "Disqualification from a competition or prize category.", "Removal from the event.", "Restriction from future GoldenHour events.", "Referral to venue authorities or appropriate authorities where necessary."],},
  { title: "15. No Retaliation", paragraphs: ["Retaliation against someone who makes a good-faith report, participates in an investigation, provides evidence, or supports another participant making a report is not permitted.", "False reports made deliberately to harm another person may themselves violate this Code of Conduct. However, a report made in good faith will not be treated as misconduct simply because the investigation does not substantiate the allegation."] },
  { title: "16. Fairness and Due Process", paragraphs: ["GoldenHour will make reasonable efforts to handle incidents consistently and fairly.", "The organizers may consider:"], bullets: ["The seriousness of the conduct.", "Whether anyone was placed at risk.", "Whether the behavior was repeated.", "Available evidence.", "The circumstances surrounding the incident.", "Previous relevant violations during the event."],},
  { title: "17. Cooperation", paragraphs: ["By participating in GoldenHour, you agree to cooperate with reasonable event procedures, including:"], bullets: ["Registration and identity verification requirements.", "Venue security procedures.", "Event rules.", "Judging and submission procedures.", "Reasonable investigations into Code of Conduct violations."],},
  { title: "18. Scope", paragraphs: ["This Code of Conduct applies throughout the GoldenHour experience, including:"], bullets: ["The physical event venue.", "Official GoldenHour online communities.", "Official event communication channels.", "Official event activities.", "Events or activities directly associated with GoldenHour.", "Sponsors, judges, volunteers, organizers, guests, and other non-participant attendees are expected to follow the same standards."]},
];

export default function CodeOfConductPage() {
  return (
    <main className="min-h-screen bg-offwhite px-5 md:px-12 py-24 md:py-36">
      <article className="max-w-[900px] mx-auto">
        <Link href="/goldenhour" className="font-space text-xs text-sunset hover:text-black">← BACK TO GOLDENHOUR V1</Link>
        <p className="font-space text-xs text-black/50 mt-14 mb-5">EFFECTIVE FOR ALL GOLDENHOUR EVENTS, INCLUDING GOLDENHOUR V1</p>
        <h1 className="font-archivo text-5xl sm:text-7xl md:text-8xl leading-[.82]">CODE OF<br /><span className="text-sunset">CONDUCT.</span></h1>
        <div className="mt-12 space-y-12 font-dm text-base md:text-lg leading-relaxed text-black/75">
          <p>GoldenHour is committed to creating a safe, respectful, inclusive, and welcoming environment where students can learn, build, collaborate, and share ideas.</p>
          <p>This Code of Conduct applies to every person participating in or associated with a GoldenHour event, including participants, volunteers, organizers, speakers, sponsors, judges, guests, photographers, and event staff.</p>
          <p>By registering for, attending, volunteering at, or otherwise participating in GoldenHour, you agree to follow this Code of Conduct.</p>
          {sections.map((section) => <section key={section.title} className="border-t-2 border-black/15 pt-8"><h2 className="font-archivo text-2xl md:text-3xl text-black mb-6">{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph} className="mb-5">{paragraph}</p>)}{section.bullets && <ul className="list-disc pl-6 space-y-3">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}
          <section className="border-t-2 border-black/15 pt-8"><h2 className="font-archivo text-2xl md:text-3xl text-black mb-6">REPORTING CONTACT</h2><p><strong>GoldenHour Organizing Team</strong><br />Email: <a className="underline text-sunset" href="mailto:goldenhourdelhi@gmail.com">goldenhourdelhi@gmail.com</a></p><p className="mt-5">For urgent incidents during the event, approach any clearly identified GoldenHour organizer or volunteer and ask for the event lead.</p></section>
          <section className="border-t-2 border-black/15 pt-8"><h2 className="font-archivo text-2xl md:text-3xl text-black mb-6">OUR COMMITMENT</h2><p>GoldenHour exists to give people a place to <strong>build, learn, experiment, collaborate, and meet other builders</strong>.</p><p className="mt-5">We want participants to be able to focus on creating great projects without worrying about harassment, intimidation, discrimination, or unsafe behavior.</p><p className="mt-5">By participating in GoldenHour, you help create that environment.</p><p className="mt-8 font-archivo text-2xl text-sunset">Build boldly. Treat people respectfully. Leave the community better than you found it.</p></section>
          <p className="border-t-2 border-black/15 pt-8 font-space text-xs text-black/55">LAST UPDATED: SEPTEMBER 2026<br />GOLDENHOUR<br />CONTACT: <a className="underline text-sunset" href="mailto:goldenhourdelhi@gmail.com">goldenhourdelhi@gmail.com</a></p>
        </div>
      </article>
    </main>
  );
}

