"use client";
import { useEffect, useState } from "react";
import { eventConfig } from "@/lib/event";

export default function Countdown() {
  const [timeLeft, setTimeLeft] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  useEffect(() => { const target = new Date(eventConfig.isoDate).getTime(); const update = () => { const diff = Math.max(0, target - Date.now()); setTimeLeft({ days: Math.floor(diff / 86400000), hours: Math.floor((diff / 3600000) % 24), minutes: Math.floor((diff / 60000) % 60), seconds: Math.floor((diff / 1000) % 60) }); }; update(); const id = setInterval(update, 1000); return () => clearInterval(id); }, []);
  const pad = (n: number) => String(n).padStart(2, "0");
  const units = [{ value: pad(timeLeft.days), label: "DAYS" }, { value: pad(timeLeft.hours), label: "HOURS" }, { value: pad(timeLeft.minutes), label: "MINUTES" }, { value: pad(timeLeft.seconds), label: "SECONDS" }];
  return <section id="countdown" className="bg-black py-28 md:py-40 px-5 md:px-10 relative overflow-hidden border-y-4 border-sunset"><div className="absolute top-8 left-8 w-6 h-6 border-2 border-sunset/30 rotate-45" /><div className="absolute bottom-10 right-16 w-12 h-12 border border-sunset/20 rounded-full" /><div className="max-w-[1240px] mx-auto relative z-10 reveal text-center"><div className="mb-14"><p className="font-space text-xs text-sunset uppercase tracking-[.18em] mb-5 font-bold">UNTIL THE HOUR</p><h2 className="font-archivo text-4xl md:text-6xl text-offwhite">THE CLOCK <span className="text-sunset">IS RUNNING.</span></h2><p className="font-space text-[10px] text-offwhite/45 uppercase leading-relaxed mt-6">{eventConfig.date} ({eventConfig.dateStatus}) / 09:00 / {eventConfig.location} / <span className="text-offwhite/75">10 HOURS OF MAKING</span></p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-5 border-t border-offwhite/15 pt-10 max-w-[1080px] mx-auto">{units.map((item) => <div key={item.label} className="text-center"><span className="font-archivo text-[18vw] sm:text-[15vw] md:text-[8vw] text-offwhite leading-[.8] block">{item.value}</span><span className="font-space text-[9px] md:text-[10px] text-offwhite/40 uppercase tracking-widest font-bold block mt-4">{item.label}</span></div>)}</div></div></section>;
}
