"use client";
import { useEffect, useState } from "react";

export default function Countdown() {
  const [timeLeft, setTimeLeft] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  useEffect(() => { const target = new Date("2026-11-15T09:00:00+05:30").getTime(); const update = () => { const diff = Math.max(0, target - Date.now()); setTimeLeft({ days: Math.floor(diff / 86400000), hours: Math.floor((diff / 3600000) % 24), minutes: Math.floor((diff / 60000) % 60), seconds: Math.floor((diff / 1000) % 60) }); }; update(); const id = setInterval(update, 1000); return () => clearInterval(id); }, []);
  const pad = (n: number) => String(n).padStart(2, "0"); const units = [{ value: pad(timeLeft.days), label: "DAYS" }, { value: pad(timeLeft.hours), label: "HOURS" }, { value: pad(timeLeft.minutes), label: "MINUTES" }];
  return <section className="bg-black py-28 md:py-40 px-5 md:px-12 relative overflow-hidden border-y-4 border-sunset"><div className="absolute top-8 left-8 w-6 h-6 border-2 border-sunset/30 rotate-45" /><div className="absolute bottom-10 right-16 w-12 h-12 border border-sunset/20 rounded-full" /><div className="max-w-[1100px] mx-auto relative z-10 reveal text-center"><div className="mb-14"><p className="font-space text-xs text-sunset uppercase tracking-[.18em] mb-5 font-bold">UNTIL THE HOUR</p><h2 className="font-archivo text-4xl md:text-6xl text-offwhite">THE CLOCK <span className="text-sunset">IS RUNNING.</span></h2><p className="font-space text-[10px] text-offwhite/45 uppercase leading-relaxed mt-6">NOVEMBER 15, 2026 / 09:00 / DELHI, INDIA / <span className="text-offwhite/75">48 HOURS OF MAKING</span></p></div><div className="flex items-start justify-center gap-2 md:gap-7 border-t border-offwhite/15 pt-10">{units.map((item, i) => <div key={item.label} className="flex items-start gap-2 md:gap-7"><div><span className="font-archivo text-[20vw] md:text-[10vw] lg:text-[8vw] text-offwhite leading-[.8] block">{item.value}</span><span className="font-space text-[9px] md:text-[10px] text-offwhite/40 uppercase tracking-widest font-bold block mt-3">{item.label}</span></div>{i < 2 && <span className="font-archivo text-3xl md:text-5xl text-sunset mt-1 md:mt-3">:</span>}</div>)}</div></div></section>;
}
