"use client";
import { ArrowUpRight, Code2, Gamepad2 } from "lucide-react";

const tracks = [
  { num: "01", label: "TRACK ONE", title: "WEB DEVELOPMENT", description: "Design and ship a web experience from the first wireframe to the first real user. Frontend, backend, product, systems — choose your surface and make it work.", icon: <Code2 size={42} />, meta: "BUILD / SHIP / ITERATE", tone: "bg-offwhite" },
  { num: "02", label: "TRACK TWO", title: "GAME DEVELOPMENT", description: "Build a playable world with a mechanic worth remembering. Make the loop feel good, make the rules interesting, and get someone else to play it.", icon: <Gamepad2 size={42} />, meta: "PLAY / TEST / REPEAT", tone: "bg-black text-offwhite" },
];

export default function Events() { return <section id="events" className="bg-offwhite py-28 md:py-40 px-5 md:px-12 relative overflow-hidden grid-pattern"><div className="max-w-[1120px] mx-auto relative z-10"><div className="text-center max-w-3xl mx-auto mb-16 md:mb-20 reveal"><div className="inline-block font-space text-[10px] font-bold bg-black text-offwhite px-3 py-1 mb-6">02 / TRACKS</div><h2 className="font-archivo text-6xl sm:text-7xl md:text-8xl text-black">CHOOSE<br />YOUR TRACK<span className="text-sunset">.</span></h2><p className="font-space text-xs md:text-sm text-black/55 max-w-md mx-auto mt-6 leading-relaxed">Two ways in. One shared finish line.<br />Build something you can show.</p></div><div className="grid md:grid-cols-2 gap-8 md:gap-10 max-w-[980px] mx-auto">{tracks.map((track, index) => <article key={track.num} className={`brutal-card p-8 md:p-10 min-h-[450px] flex flex-col justify-between relative overflow-hidden reveal ${index === 0 ? "delay-1 rotate-[-.5deg]" : "delay-2 rotate-[.5deg]"} ${track.tone}`}><div><div className="flex items-start justify-between mb-12"><div className="w-16 h-16 border-2 border-black bg-black text-offwhite flex items-center justify-center font-archivo text-2xl">{track.num}</div><div className={index === 1 ? "text-offwhite/25" : "text-sunset/60"}>{track.icon}</div></div><span className={`font-space text-[10px] font-bold px-2 py-1 uppercase inline-block mb-5 border border-black ${index === 1 ? "bg-offwhite text-black" : "bg-sunset text-black"}`}>{track.label}</span><h3 className={`font-archivo text-4xl md:text-5xl leading-[.85] mb-6 ${index === 1 ? "text-offwhite" : "text-black"}`}>{track.title}</h3><p className={`font-space text-xs leading-relaxed max-w-md ${index === 1 ? "text-offwhite/65" : "text-black/65"}`}>{track.description}</p></div><div><div className={`flex items-center justify-between border-t pt-5 mb-5 ${index === 1 ? "border-offwhite/20" : "border-black/15"}`}><span className="font-space text-[9px] uppercase opacity-60">{track.meta}</span><ArrowUpRight size={18} className="text-sunset" /></div><a href="#register" className={`brutal-btn w-full py-4 text-xs ${index === 1 ? "bg-offwhite text-black hover:bg-sunset" : ""}`}>ENTER TRACK <ArrowUpRight size={14} /></a></div></article>)}</div><div className="mt-14 max-w-[980px] mx-auto border-2 border-black bg-sunset shadow-[7px_7px_0_#050505] p-7 md:p-9 text-center reveal delay-3"><p className="font-space text-[10px] font-bold tracking-[.18em] mb-3">THE ONE THING YOU DON&apos;T NEED TO KNOW YET</p><h3 className="font-archivo text-3xl sm:text-4xl md:text-5xl">THEME WILL BE REVEALED ON SPOT<span className="text-offwhite">.</span></h3></div></div></section>; }
