"use client";
import { ArrowRight, Check, Loader2, Mail } from "lucide-react";
import { useState } from "react";

export default function FinalCTA() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle"); const [error, setError] = useState("");
  function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); if (name.trim().length < 2) { setError("Tell us your name so we know who is joining."); setStatus("error"); return; } if (!/^\S+@\S+\.\S+$/.test(email)) { setError("That email needs one @ and a real domain."); setStatus("error"); return; } setStatus("loading"); window.setTimeout(() => setStatus("success"), 700); }
  return <section id="register" className="bg-sunset py-24 md:py-36 px-5 md:px-12 relative overflow-hidden border-t-4 border-black">
    <div className="absolute inset-0 opacity-25 pointer-events-none" aria-hidden="true"><div className="absolute -right-16 -top-16 w-72 h-72 rounded-full border-[3px] border-black" /><div className="absolute right-4 top-4 w-56 h-56 rounded-full border border-black" /><div className="absolute left-[8%] bottom-16 w-16 h-16 border-2 border-black rotate-45" /><span className="absolute left-[15%] top-24 font-space text-4xl">✳</span></div>
    <div className="max-w-[1100px] mx-auto relative z-10 reveal text-center"><div className="flex items-center justify-center gap-3 mb-7"><span className="w-3 h-3 bg-black" /><p className="font-space text-xs text-black/65 uppercase tracking-[.18em] font-bold">DON&apos;T WATCH. BUILD.</p></div>
      <h2 className="font-archivo text-[16vw] md:text-[9vw] lg:text-[7.5rem] text-black leading-[.79] mb-12">YOUR HOUR<br />STARTS NOW<span className="text-offwhite">.</span></h2>
      {status === "success" ? <div className="bg-black text-offwhite border-2 border-black shadow-[7px_7px_0_#f7f7f2] p-6 md:p-8 max-w-xl mx-auto text-left"><div className="flex items-center gap-3 text-sunset mb-3"><Check size={20} /><span className="font-space text-xs font-bold">SIGNAL RECEIVED</span></div><p className="font-archivo text-2xl">YOU&apos;RE ON THE LIST.</p><p className="font-dm text-sm text-offwhite/65 mt-3">We&apos;ll send the next coordinates to {email}.</p></div> : <form onSubmit={submit} noValidate className="max-w-[760px] mx-auto text-left"><div className="grid sm:grid-cols-2 gap-5"><label className="font-space text-[10px] font-bold uppercase">Name<input value={name} onChange={(e) => setName(e.target.value)} aria-invalid={status === "error" && name.trim().length < 2} className="mt-2 w-full border-2 border-black bg-offwhite px-4 py-3 font-dm text-black outline-none focus:ring-2 focus:ring-black" autoComplete="name" />{status === "error" && name.trim().length < 2 && <span className="block mt-2 normal-case text-[10px] text-black/70">Please enter at least 2 characters.</span>}</label><label className="font-space text-[10px] font-bold uppercase">Email<input value={email} onChange={(e) => setEmail(e.target.value)} aria-invalid={status === "error" && !/^\S+@\S+\.\S+$/.test(email)} className="mt-2 w-full border-2 border-black bg-offwhite px-4 py-3 font-dm text-black outline-none focus:ring-2 focus:ring-black" type="email" autoComplete="email" />{status === "error" && !/^\S+@\S+\.\S+$/.test(email) && <span className="block mt-2 normal-case text-[10px] text-black/70">Enter a valid email address.</span>}</label></div>{error && <p className="font-space text-xs font-bold mt-4" role="alert">ERROR: {error}</p>}<div className="flex flex-col sm:flex-row gap-4 mt-7 justify-center"><button disabled={status === "loading"} className="brutal-btn px-8 py-5 text-sm md:text-base disabled:opacity-60">{status === "loading" ? <><Loader2 size={18} className="animate-spin" /> SENDING...</> : <>REGISTER INTEREST <ArrowRight size={18} /></>}</button><a href="mailto:hello@goldenhour.dev" className="inline-flex items-center justify-center gap-2 font-space text-xs font-bold uppercase underline underline-offset-4 hover:no-underline">Questions? Say hello <Mail size={15} /></a></div></form>}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-6 border-t-2 border-black/20 pt-7 mt-16 text-center">{[["DATE", "NOV 2026"], ["LOCATION", "DELHI, INDIA"], ["DURATION", "10 HOURS"], ["COST", "FREE"]].map(([label, value]) => <div key={label}><p className="font-space text-[10px] text-black/45 uppercase font-bold mb-1">{label}</p><p className="font-space text-xs font-bold text-black">{value}</p></div>)}</div>
    </div>
  </section>;
}
