"use client";
import Image from "next/image";

const explore = [["ABOUT", "#about"], ["TRACKS", "#events"], ["TIMELINE", "#timeline"], ["PRIZES", "#prizes"], ["RULES", "#rules"], ["ORGANIZERS", "#organizers"], ["FAQ", "#faq"]];
import { eventConfig } from "@/lib/event";

export default function Footer() {
  return <footer className="bg-black text-offwhite px-5 md:px-10 py-24 md:py-32 border-t-4 border-sunset">
    <div className="max-w-[1240px] mx-auto">
      <div className="text-center pb-16 md:pb-20 border-b border-offwhite/15"><div className="inline-flex p-3 md:p-4"><Image src="/brand/goldenhour-symbol-transparent.png" alt="GoldenHour logo" width={500} height={500} className="block w-28 h-28 md:w-36 md:h-36 object-contain mx-auto" /></div><p className="font-dm text-lg md:text-xl text-offwhite/65 max-w-xl mx-auto mt-8 leading-relaxed">A student-built experience for people who make things before they feel ready.</p><div className="flex justify-center items-center gap-3 mt-7"><span className="w-10 h-1 bg-sunset" /><span className="font-space text-[10px] text-sunset font-bold uppercase tracking-[.15em]">DELHI / 14 NOVEMBER 2026 (TENTATIVE) / VENUE TBA</span><span className="w-10 h-1 bg-sunset" /></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-12 md:gap-16 py-16 md:py-20 text-center md:text-left"><div className="col-span-2 md:col-span-1"><p className="font-space text-[10px] font-bold text-sunset uppercase tracking-[.16em] mb-6">THE ORGANIZING TEAM</p><address className="not-italic font-space text-xs text-offwhite/55 leading-loose">GOLDENHOUR<br />DELHI / VENUE TBA<br /><a href="mailto:goldenhourdelhi@gmail.com" className="text-offwhite hover:text-sunset transition-colors">goldenhourdelhi@gmail.com</a></address></div><div><p className="font-space text-[10px] font-bold text-sunset uppercase tracking-[.16em] mb-6">EXPLORE</p><ul className="font-space text-xs space-y-4 text-offwhite/55">{explore.map(([label, href]) => <li key={href}><a href={href} className="hover:text-offwhite transition-colors">{label}</a></li>)}</ul></div><div><p className="font-space text-[10px] font-bold text-sunset uppercase tracking-[.16em] mb-6">CONNECT</p><ul className="font-space text-xs space-y-4 text-offwhite/55"><li><a href={eventConfig.registrationUrl} target="_blank" rel="noreferrer" className="hover:text-sunset transition-colors">REGISTER NOW</a></li><li><a href={eventConfig.volunteerUrl} target="_blank" rel="noreferrer" className="hover:text-sunset transition-colors">VOLUNTEER FORM</a></li><li><a href={eventConfig.whatsappCommunityUrl} target="_blank" rel="noreferrer" className="hover:text-sunset transition-colors">WHATSAPP COMMUNITY</a></li><li><a href="mailto:goldenhourdelhi@gmail.com" className="hover:text-sunset transition-colors">EMAIL THE TEAM</a></li><li><a href="/privacy" className="hover:text-sunset transition-colors">PRIVACY</a></li><li><a href="/terms" className="hover:text-sunset transition-colors">TERMS</a></li></ul></div><div className="col-span-2 md:col-span-1 text-center md:text-left"><p className="font-space text-[10px] font-bold text-sunset uppercase tracking-[.16em] mb-6">THE EVENT</p><p className="font-archivo text-3xl leading-[.9]">BUILD<br />BEFORE<br /><span className="text-sunset">SUNRISE.</span></p><a href={eventConfig.registrationUrl} target="_blank" rel="noreferrer" className="brutal-btn-orange inline-flex mt-6 text-xs">REGISTER NOW <span aria-hidden="true">↗</span></a></div></div>
      <div className="pt-8 border-t border-offwhite/15 flex flex-col sm:flex-row justify-center sm:justify-between items-center gap-5 text-center"><p className="font-space text-[10px] text-offwhite/35 tracking-[.08em]">MADE BY TEENS. FOR TEENS.</p><a href="#hero" className="font-space text-[10px] text-offwhite/35 hover:text-offwhite transition-colors">BACK TO TOP ↑</a></div>
    </div>
  </footer>;
}
