"use client";
import Image from "next/image";
import { ArrowUpRight, ExternalLink } from "lucide-react";

const volunteerUrl = "https://forms.gle/R8cuBKNLj1ftXKfJ8";

const sponsors = [
  { name: "NERDSROOM", role: "LEAD SPONSOR", href: "https://nerdsroom.xyz", logo: "/brand/nerdsroom-logo.png", alt: "NerdsRoom logo", width: 220, height: 220, visit: "VISIT NERDSROOM" },
  { name: "CODECRAFTERS", role: "PRIZE SPONSOR", href: "https://www.codecrafters.io", logo: "/brand/codecrafters-logo.svg", alt: "CodeCrafters logo", width: 220, height: 155, visit: "VISIT CODECRAFTERS" },
];

export default function Sponsors() {
  return <section className="bg-black py-28 md:py-40 px-5 md:px-10 relative overflow-hidden"><div className="max-w-[1240px] mx-auto relative z-10"><div className="text-center max-w-3xl mx-auto mb-16 border-b-2 border-offwhite/15 pb-10 reveal"><div className="inline-block font-space text-[10px] font-bold bg-yellow text-black px-3 py-1 mb-5 uppercase">SPONSORS / CONFIRMED</div><h2 className="font-archivo text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-offwhite">BACK THE<br /><span className="text-sunset">BUILD.</span></h2><p className="font-space text-xs text-offwhite/45 max-w-sm leading-relaxed mx-auto mt-7">NerdsRoom is leading the build. CodeCrafters is powering the prizes.</p></div><div className="grid md:grid-cols-2 gap-6 max-w-[1100px] mx-auto">{sponsors.map((sponsor) => <a key={sponsor.name} href={sponsor.href} target="_blank" rel="noreferrer" className="group brutal-card p-8 md:p-10 text-center flex flex-col items-center justify-center min-h-[360px] reveal"><p className="font-space text-[10px] uppercase tracking-[.16em] text-black/55 mb-8">{sponsor.role}</p><div className="bg-offwhite border-2 border-black p-7 w-full max-w-[310px] h-[190px] flex items-center justify-center"><Image src={sponsor.logo} alt={sponsor.alt} width={sponsor.width} height={sponsor.height} className="max-w-[220px] max-h-[150px] w-auto h-auto object-contain" /></div><h3 className="font-archivo text-4xl mt-8">{sponsor.name}</h3><p className="font-space text-[10px] uppercase tracking-[.14em] mt-4 inline-flex items-center gap-2 group-hover:text-sunset">{sponsor.visit} <ExternalLink size={14} /></p></a>)}</div><div className="max-w-[760px] mx-auto mt-10 brutal-card-orange p-8 md:p-12 text-center reveal"><p className="font-space text-[10px] uppercase tracking-[.16em] mb-5">SPONSOR OPPORTUNITIES / 2026</p><h3 className="font-archivo text-4xl md:text-6xl leading-[.82]">SPONSOR<br />SLOTS<br /><span className="text-offwhite">OPEN.</span></h3><p className="font-dm text-base md:text-lg mt-8 max-w-md mx-auto leading-relaxed">Want to support student builders or sponsor a future GOLDENHOUR edition? Email the organizing team to start a conversation.</p><a href="mailto:goldenhourdelhi@gmail.com?subject=GOLDENHOUR%20sponsorship" className="font-space text-xs font-bold uppercase flex items-center justify-center gap-2 mt-8 hover:text-offwhite">CONTACT US TO SPONSOR <ArrowUpRight size={15} /></a><a href={volunteerUrl} target="_blank" rel="noreferrer" className="font-space text-xs font-bold uppercase flex items-center justify-center gap-2 mt-5 text-black/65 hover:text-offwhite">VOLUNTEER WITH US <ArrowUpRight size={15} /></a></div><p className="font-space text-[10px] text-offwhite/30 uppercase tracking-[.16em] mt-10 text-center reveal">GOLDENHOUR / NERDSROOM / CODECRAFTERS</p></div></section>;
}
