"use client";
import { ArrowUpRight, ExternalLink } from "lucide-react";

const sponsorUrl = "https://www.codecrafters.io";
const volunteerUrl = "https://forms.gle/R8cuBKNLj1ftXKfJ8";

export default function Sponsors() {
  return <section className="bg-black py-28 md:py-40 px-5 md:px-10 relative overflow-hidden"><div className="max-w-[1240px] mx-auto relative z-10"><div className="text-center max-w-3xl mx-auto mb-16 border-b-2 border-offwhite/15 pb-10 reveal"><div className="inline-block font-space text-[10px] font-bold bg-yellow text-black px-3 py-1 mb-5 uppercase">SPONSORS / CONFIRMED</div><h2 className="font-archivo text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-offwhite">BACK THE<br /><span className="text-sunset">BUILD.</span></h2><p className="font-space text-xs text-offwhite/45 max-w-sm leading-relaxed mx-auto mt-7">CodeCrafters is joining GOLDENHOUR as the official prize sponsor.</p></div><div className="grid lg:grid-cols-[1fr_1.15fr] gap-6 max-w-[1100px] mx-auto items-stretch"><a href={sponsorUrl} target="_blank" rel="noreferrer" className="group brutal-card p-8 md:p-10 text-center flex flex-col items-center justify-center min-h-[320px] reveal"><p className="font-space text-[10px] uppercase tracking-[.16em] text-black/55 mb-8">PRIZE SPONSOR</p><div className="bg-offwhite border-2 border-black p-7 w-full max-w-[310px] flex items-center justify-center"><img src="/brand/codecrafters-logo.svg" alt="CodeCrafters logo" className="w-full max-w-[220px] h-auto" /></div><h3 className="font-archivo text-4xl mt-8">CODECRAFTERS</h3><p className="font-space text-[10px] uppercase tracking-[.14em] mt-4 inline-flex items-center gap-2 group-hover:text-sunset">VISIT CODECRAFTERS <ExternalLink size={14} /></p></a><div className="brutal-card-orange p-8 md:p-12 text-center reveal"><p className="font-space text-[10px] uppercase tracking-[.16em] mb-5">SPONSOR OPPORTUNITIES / 2026</p><h3 className="font-archivo text-4xl md:text-6xl leading-[.82]">SPONSOR<br />SLOTS<br /><span className="text-offwhite">OPEN.</span></h3><p className="font-dm text-base md:text-lg mt-8 max-w-md mx-auto leading-relaxed">Want to support student builders or sponsor a future GOLDENHOUR edition? Email the organizing team to start a conversation.</p><a href="mailto:goldenhourdelhi@gmail.com?subject=GOLDENHOUR%20sponsorship" className="font-space text-xs font-bold uppercase flex items-center justify-center gap-2 mt-8 hover:text-offwhite">CONTACT US TO SPONSOR <ArrowUpRight size={15} /></a><a href={volunteerUrl} target="_blank" rel="noreferrer" className="font-space text-xs font-bold uppercase flex items-center justify-center gap-2 mt-5 text-black/65 hover:text-offwhite">VOLUNTEER WITH US <ArrowUpRight size={15} /></a></div></div><p className="font-space text-[10px] text-offwhite/30 uppercase tracking-[.16em] mt-10 text-center reveal">GOLDENHOUR / CODECRAFTERS / PRIZE SPONSOR</p></div></section>;
}
