import Link from "next/link";
import { eventConfig } from "@/lib/event";
import { pageMetadata } from "../metadata";

export const metadata = pageMetadata("Terms & Conditions", "Participation terms for GoldenHour V1, including eligibility, consent, verification, project rules, deadline and event changes.", "/terms");

export default function TermsPage() {
  return <main className="min-h-screen bg-offwhite px-5 md:px-12 py-24 md:py-36"><article className="legal-document max-w-[850px] mx-auto"><Link href="/goldenhour" className="font-space text-xs text-sunset hover:text-black">← BACK TO GOLDENHOUR V1</Link><p className="font-space text-xs text-black/50 mt-14 mb-5">LAST UPDATED / 30 SEPTEMBER 2026</p><h1 className="font-archivo text-6xl md:text-8xl">TERMS &amp;<br /><span className="text-sunset">CONDITIONS.</span></h1><div className="mt-12 space-y-8 font-dm text-base md:text-lg leading-relaxed text-black/75">
    <p>These terms apply to participation in GoldenHour V1. The event is free and is scheduled for {eventConfig.date}, in Delhi NCR. The date is tentative and the venue has not yet been confirmed; schedule, venue and logistics may change. We will share material updates using the contact information provided at registration.</p>
    <section><h2 className="font-archivo text-2xl text-black mb-3">ELIGIBILITY &amp; TEAM SIZE</h2><p>Each participant must be at least 13 and under 20 on 14 November 2026 (ages 13–19 on the event date). Teams may have one, two or three participants. The team leader submits one form and includes every team member. Participation is subject to available capacity and organizer confirmation.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">PARENT/GUARDIAN CONSENT &amp; AGE CHECK</h2><p>Participants under 18 need parent or legal guardian consent. Consent is requested during registration, and a signed guardian consent slip must be brought to check-in. At check-in, organizers may view a school ID, Aadhaar, passport, or birth certificate to verify age. They will not copy or store that document.</p><p className="mt-3">Participants are responsible for arranging their own travel. Overnight accommodation is not provided. Until the venue is confirmed, these travel details are provisional. A parent or guardian must arrange the journey home for a participant under 18.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">PROJECT RULES &amp; AI DISCLOSURE</h2><p>The project must be started at the event. Teams may use open-source libraries, templates and their own reusable boilerplate, subject to applicable licenses. AI tools are allowed; teams must disclose the tools they used in the project README. Teams must follow third-party licenses, credit external work appropriately, and submit work they are permitted to use.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">SUBMISSION DEADLINE</h2><p>Project submissions close at <strong>5:00 PM IST sharp</strong> on event day. Required submission materials include a public project repository, a README and a working demo link. Late submissions cannot be accepted. The organizing team will publish the submission instructions before the event.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">AWARDS</h2><p>A winning team receives one GoldenHour trophy per team. CodeCrafters VIP memberships and other participant prizes are awarded per participant as described in the published prize details.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">CODE OF CONDUCT</h2><p>All attendees must follow the <Link className="underline text-sunset" href="/code-of-conduct">GoldenHour Code of Conduct</Link> and reasonable venue and event-safety instructions. The organizers may take proportionate action for rule violations, including removal from an activity or event or disqualification where appropriate.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">CONTACT</h2><p>Questions about these terms can be sent to <a className="underline text-sunset" href={`mailto:${eventConfig.contactEmail}`}>{eventConfig.contactEmail}</a>.</p></section>
  </div></article></main>;
}
