import Link from "next/link";
import { eventConfig } from "@/lib/event";
import { pageMetadata } from "../metadata";

export const metadata = pageMetadata("Privacy Policy", "How GoldenHour handles event-registration and website information, including guardian consent and age-check documents.", "/privacy");

export default function PrivacyPage() {
  return <main className="min-h-screen bg-offwhite px-5 md:px-12 py-24 md:py-36"><article className="legal-document max-w-[850px] mx-auto"><Link href="/goldenhour" className="font-space text-xs text-sunset hover:text-black">← BACK TO GOLDENHOUR V1</Link><p className="font-space text-xs text-black/50 mt-14 mb-5">LAST UPDATED / 30 SEPTEMBER 2026</p><h1 className="font-archivo text-6xl md:text-8xl">PRIVACY<br /><span className="text-sunset">POLICY.</span></h1><div className="mt-12 space-y-8 font-dm text-base md:text-lg leading-relaxed text-black/75">
    <p>GoldenHour is a student-led event organized in Delhi NCR, India. This policy explains how the organizing team handles information people choose to provide when they register, contact us, or use this website.</p>
    <section><h2 className="font-archivo text-2xl text-black mb-3">REGISTRATION INFORMATION</h2><p>The registration form is hosted by Google Forms. A team leader submits one registration for the team. The form asks for the team name, size and track, school, and each listed member’s name, class, email, WhatsApp/phone number, gender (including a “rather not say” choice), and emergency contact; GitHub links are optional. Information is used to administer registration, coordinate teams and event participation, communicate event updates, and manage age and guardian-consent requirements. Do not enter dates of birth or upload identity documents. Google handles the form and its storage under its own service terms and privacy practices.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">UNDER-18 PARTICIPANTS</h2><p>Participants under 18 need parent or legal guardian consent. The registration process requests the relevant consent information, and a signed guardian consent slip is required at check-in. A guardian may contact us at the address below with a question or request about a minor&apos;s registration information.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">AGE VERIFICATION</h2><p>At check-in, organizers may view a school ID, Aadhaar, passport, or birth certificate solely to verify that a participant is eligible. Organizers will not copy, photograph, or store the identity document. Please do not email us a copy of an identity document.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">WEBSITE ANALYTICS &amp; COOKIES</h2><p>Optional, privacy-conscious analytics run only if you allow them in the cookie banner. You can choose essential storage only. The site stores your choice so it can honor that preference; essential storage may still be used for site functionality.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">RETENTION, ACCESS &amp; DELETION</h2><p>We do not publish a fixed retention period for registration responses. To request a copy of registration information, ask for a correction, or request deletion, email <a className="underline text-sunset" href={`mailto:${eventConfig.contactEmail}`}>{eventConfig.contactEmail}</a>. The organizing team aims to respond within 30 days. A request about a participant under 18 may be sent by their parent or legal guardian.</p></section>
    <section><h2 className="font-archivo text-2xl text-black mb-3">CONTACT</h2><p>For privacy questions, contact the GoldenHour organizing team at <a className="underline text-sunset" href={`mailto:${eventConfig.contactEmail}`}>{eventConfig.contactEmail}</a>.</p></section>
  </div></article></main>;
}
